### ISSUE TITLE
How can I use a new character?

### ISSUE THREAD

**Issue by linmanqing** [sreyafrancis/PFNN#2]
Hello! 

I try to change the character, which has different joint positions with the original character. 
However, it seems to change joint positions of the new character to be similar with original one, and distort the character to fit this change. As a result, the character looks terrible.

I wonder how I can use a new character with different joint positions?  Do I need to retrain the model with new character?
An other question is, can I reduce the number of joint points? Do I need to retrain the model?

Looking forward to your reply. Thank you very much.

**Comment by sreyafrancis** [comment]
Hello,

Various things including the skeleton structure are somewhat hard-coded so be careful if you are using your own data and own network weights and want to update them.

Hence it is highly recommended that you retrain the model with your specific requirements.
However you have to do proper pre-processing before doing the same.

You have to build the database of terrain patches which are later 
fitted to the motion. For this simply run the following. 

    python generate_patches.py

This will sample thousands of patches from the heightmaps found in 
`data/heightmaps` and store them in a database called `patches.npz`. This
should take a good few minutes so be patient.

Now you can begin the process of preprocessing the animation data - converting 
it into the correct format and fitting the terrain to each walk cycle. For this
you run the following:

    python generate_database.py

This process can take some time - at least a couple of hours. It uses all the 
data found in `data/animations` and once complete will output a database called 
`database.npz`. If you want to change the parameterisation used by the network 
this is probably the place to look - but note that the preprocessing for this 
work is quite fiddily and complicated so you must be careful when you edit this 
script not to introduce any bugs. You will also have to remember to update the
runtime to match.

Once you've generated `database.npz` you can begin training.

**Comment by linmanqing** [comment]
Thank you very much. 
You said 'Various things including the skeleton structure are somewhat hard-coded', and I wonder what is 'skeleton structure'? Does it include the 3D locations of the joints? If I have a character which has the same skeleton basic structure (I mean the same joint index, the same father&son joints relationship) and the different joint locations, can I input the character to the trained model in this code without retraining?
